Xpos334/Xpos334/Controllers/CategoryTryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Policy;
using xpos334.datamodels;
using xpos334.viewmodels;
using Xpos334.Services;

namespace Xpos334.Controllers

{
    public class CategoryTryController : Controller
    {

        private readonly XPOS_334Context db;
        private readonly CategoryTryService categoryServices;


        public CategoryTryController(XPOS_334Context _db)
        {
            db = _db;
            this.categoryServices = new CategoryTryService(db);
        }

        public IActionResult Index()
        {
            List<VMTblCategory> dataView = categoryServices.GetAllData();
            return View(dataView);
        }

        public IActionResult Create()
        {
            VMTblCategory dataView = new VMTblCategory();
            return PartialView(dataView);
        }
        [HttpPost]
        
        public IActionResult Create(VMTblCategory dataView) 
        {
            VMResponse respon = new VMResponse();
            if(ModelState.IsValid)
            {
                respon = categoryServices.Create(dataView);

                if(respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblCategory dataView = categoryServices.GetById(id);
            return PartialView(dataView);
        }
        [HttpPost]
        public IActionResult Edit(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();
            if(ModelState.IsValid)
            {
                respon = categoryServices.Edit(dataView);
                if(respon.Success)
                {
                    return RedirectToAction("Index");
                }
                
            }
            respon.Entity = dataView;
            return View(respon.Entity);

        }

        public IActionResult Detail(int id)
        {
            VMTblCategory dataView = categoryServices.GetById(id);
            return PartialView(dataView);

       /*     ViewBag.tbl_Category = dataView;
            return View();*/
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            VMTblCategory dataView = categoryServices.GetById(id);
            return PartialView(dataView);
        }
        [HttpPost]
        public IActionResult Delete(VMTblCategory dataView)
        {
            VMResponse respon = categoryServices.Delete(dataView);
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }
            else View(respon.Entity);
            respon.Entity = dataView;
            return View(respon.Entity);
        }
    }
}

Xpos334/Xpos334/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.viewmodels;
using Xpos334.Services;

namespace Xpos334.Controllers
{
    public class ProductController : Controller
    {
        private CategoryService categoryService;
        private VariantService variantService;
        private ProductService productService;
        private readonly IWebHostEnvironment webHostEnvironment;
        private int IdUser = 1;

        public ProductController(CategoryService _categoryService, VariantService _variantService, ProductService _productService , IWebHostEnvironment _webHostEnvironment)
        {
            categoryService = _categoryService;
            productService = _productService;
            variantService = _variantService;
            webHostEnvironment = _webHostEnvironment;
        }
        
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSort = sortOrder == "Price" ? "price_desc" : "price";


            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<VMTblProduct> data = await productService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower())
                    || a.NameCategory.ToLower().Contains(searchString.ToLower())
                    || a.NameProduct.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameProduct).ToList();
                    break;
                case "price_desc":
                    data = data.OrderByDescending(a => a.Price).ToList();
                    break;
                case "price":
                    data = data.OrderBy(a => a.Price).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameProduct).ToList();
                    break;
            }

            return View(PaginatedList<VMTblProduct>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }


        public async Task<IActionResult> Create()
        {
            VMTblProduct data = new VMTblProduct();
            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            List<VMTblVariant> listVariant = await variantService.GetAllData();
            ViewBag.ListVariant = listVariant;


            return PartialView(data);
        }

        public async Task<JsonResult> GetDataByIdCategory(int id)
        {
            List<VMTblVariant> data = await variantService.GetDataByIdCategory(id);
            return Json(data);  

        }


        public async Task<JsonResult> CheckNameIsExist(string name, int id, int idVariant)
        {
            bool isExist = await productService.CheckByName(name, id, idVariant);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMTblProduct dataParam)
        {

            if (dataParam.ImageFile != null) {
                dataParam.Image = Upload(dataParam.ImageFile);
            }
            VMResponse respon = await productService.Create(dataParam);
            if(respon.Success)
            {
                return Json(new {dataRespon = respon});
            }
            return View(dataParam); 
        }

        public string Upload(IFormFile ImageFile)
        {
            string uniqueFileName = "";
            if (ImageFile != null)
            {
                string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using(var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    ImageFile.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }


        public async Task<IActionResult> Edit(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);

            //untuk drop down List
            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            //untuk drop down List
            List<VMTblVariant> listVariant = await variantService.GetAllData();
            ViewBag.ListVariant = listVariant;


            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit (VMTblProduct dataParam)
        {

            if (dataParam.ImageFile != null)
            {
                dataParam.Image = Upload(dataParam.ImageFile);
            }
            VMResponse respon = await productService.Edit(dataParam);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }



        public async Task<IActionResult> Detail(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);


            return PartialView(data);
        }


        public async Task<IActionResult> Delete(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await productService.Delete(id);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return RedirectToAction("Index");
        }


    }
}

Xpos334/Xpos334/Views/CategoryTry/Create.cshtml
@using xpos334.viewmodels;
@model VMTblCategory


@{
   // Layout = null;
    ViewData["Title"] = "Create Category Try";
}

<div class="card">
    <div class="card-body">  
        <div class="h4 mb-4" >@ViewData["Title"]</div>
        <form asp-action="Create" method="post">
            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory"value="@Model.NameCategory">
                    <span asp-validation-for="NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                    <span asp-validation-for="Description  " class="text-danger"></span>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" asp-controller="CategoryTry" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>

</div>

Xpos334/Xpos334/Views/CategoryTry/Delete.cshtml
@using xpos334.viewmodels;
@model VMTblProduct;
@{
    ViewData["Title"] = "Delete Product";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post" id="form_delete">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <h3 class="">Are you sure to delete this data <br />@Model.NameProduct</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes?</button>
                <a asp-controller="Product" asp-action="Index" class="btn btn-light">No</a>
            </div>


        </form>
    </div>
</div>


<script>
    $("#form_delete").validate({
        submitHandler: function (form) {
            //  var dataParam = $(form)
            var id = $("#Id").val()

            $.ajax({
                url: '/Category/SureDelete',
                type: "post",
                data: { id: id },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#my_modal").modal("hide")
                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        toastr.errorClass(data.message)
                    }
                }

            })
        }
    })
</script>

Xpos334/Xpos334/Views/CategoryTry/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using xpos334.viewmodels
@model VMTblCategory
@{
    ViewData["Title"] = "Detail Category Try";
}


<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>
            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
                   
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
                  
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-10">
   
                    <a class="btn btn-outline-primary" asp-controller="CategoryTry" asp-action="Index">Back To List</a>
                </div>
            </div>


    </div>

</div>

Xpos334/Xpos334/Views/CategoryTry/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using xpos334.viewmodels
@model VMTblCategory
@{
    ViewData["Title"] = "Edit";
}


<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>
        <form asp-action="Edit" method="post">
            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id"/>

            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
                    <span asp-validation-for="NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" asp-controller="CategoryTry" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>

</div>

Xpos334/Xpos334/Views/CategoryTry/Index.cshtml
@using xpos334.viewmodels;

@{
    ViewData["Title"] = "Category Try";
}


<div class="card">
    <div class="card-body">
        <h5 class="card-title">@ViewData["Title"]</h5>
        <button type="button" class="btn btn-primary" id="btn_create">Create</button>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name Category</th>
                    <th scope="col">Description</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (VMTblCategory item in Model)
                {
                <tr>
                    <td scope="row">@item.Id</td>
                    <td>@item.NameCategory</td>
                    <td>@item.Description</td> 
                    <td>
                        <a class="btn btn-outline-primary btn_edit" data-id="@item.Id">Edit</a>
                            <a class="btn btn-outline-success btn_detail" data-id="@item.Id">Detail</a>
                        <a class="btn btn-outline-danger btn_delete" data-id="@item.Id">Delete</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>

    </div>
</div>

<script>
    $("#btn_create").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Create")
        $("#my_modal").modal("show")
    })
    //edit
    $(".btn_edit").click(function ()
    { 
        var id = $(this).data("id")

        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Edit?id=" + id)
        $("#my_modal").modal("show")
    })
    //detail
    $(".btn_detail").click(function () {
        var id = $(this).data("id")

        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Detail?id=" + id)
        $("#my_modal").modal("show")
    })
    //delete
    $(".btn_delete").click(function () {
        var id = $(".btn_delete").data("id")

        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Delete?id=" + id)
        $("#my_modal").modal("show")
    })
</script>