Xpos334/Xpos334/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using xpos334.datamodels;
using xpos334.viewmodels;
using Xpos334.Services;

namespace Xpos334.Controllers
{
    public class OrderController : Controller
    {
        private ProductService productService;
        private OrderService orderService;
        private int IdUser = 1;

        public OrderController(ProductService _productService, OrderService _orderService) //activate service di contructor
        {
            productService = _productService;
            orderService = _orderService;
        }

        public async Task<IActionResult> Catalog(VMSearchPage dataSearch)
        {
            List<VMTblProduct> dataProduct = await productService.GetAllData();
            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MinAmount = dataSearch.MaxAmount ?? decimal.MaxValue; //---> Maksud nya kayak yang dibawah ini
                                                                             // dataSearch.MinAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;
            if (dataSearch.NameProduct != null)
            {
                dataProduct = dataProduct.Where(a => a.NameProduct.ToLower().Contains(dataSearch.NameProduct.ToLower())).ToList();
            }

            if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
            {
                dataProduct = dataProduct.Where(a => a.Price >= dataSearch.MinAmount &&
                                                a.Price <= dataSearch.MaxAmount).ToList();
            }

            //Get session in VMOrderHeader first Load
            VMOrderHeader dataHeader = HttpContext.Session.GetComplexData<VMOrderHeader>("ListCart");
            if (dataHeader == null)
            {
                dataHeader = new VMOrderHeader();
                dataHeader.ListDetails = new List<VMOrderDetail>();
            }
            var ListDetail = JsonConvert.SerializeObject(dataHeader.ListDetails);
            ViewBag.dataHeader = dataHeader;
            ViewBag.dataDetail = ListDetail;

            ViewBag.Search = dataSearch;
            ViewBag.CurrentPageSize = dataSearch.pageSize;

            return View(PaginatedList<VMTblProduct>.CreateAsync(dataProduct, dataSearch.pageNumber ?? 1, dataSearch.pageSize ?? 3));
        }

        //Set session in VMOrderHeader every add or minus
        [HttpPost]
        public JsonResult SetSession(VMOrderHeader dataHeader)
        {
            HttpContext.Session.SetComplexData("ListCart", dataHeader);

            return Json("");
        }

        //Remove Session
        public JsonResult RemoveSession()
        {
            HttpContext.Session.Remove("ListCart");
            //HttpContext.Session.Clear();   ---> Ini untuk hapus semua data atau sessionnya

            return Json("");
        }


        public IActionResult OrderPreview(VMOrderHeader dataHeader)
        {
            return PartialView(dataHeader);
        }

        public IActionResult SearchMenu()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> SubmitOrder(VMOrderHeader dataHeader)
        {
            dataHeader.IdCustomer = IdUser;
            //kalo id nya udah set
            // dataHeader.IdCustomer = HttpContext.Session.GetInt32("IdCostumer") ?? 0;
            dataHeader.CodeTransaction = dataHeader.CodeTransaction ?? "";

            VMResponse respon = await orderService.SubmitOrder(dataHeader);
            return Json(respon);
        }


        public async Task<IActionResult> HistoryOrder(VMSearchPage dataSearch)
        {
            // int IdCustomer = HttpContext.Session.GetInt32("IdCustomer");          --> get session dari ID Customer
            int IdCustomer = IdUser;
            List<VMOrderHeader> data = await orderService.GetDataOrderHeaderDetail(IdCustomer);
            int count = await orderService.CountTransaction(IdCustomer);
            ViewBag.Count = count;

            dataSearch.MinDate = dataSearch.MinDate == null ? DateTime.MinValue : dataSearch.MinDate;
            dataSearch.MaxDate = dataSearch.MaxDate == null ? DateTime.MaxValue : dataSearch.MaxDate;

            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;


            if (!string.IsNullOrEmpty(dataSearch.CodeTransaction))
            {
                data = data.Where(a => a.CodeTransaction.ToLower().Contains(dataSearch.CodeTransaction.ToLower())).ToList();
            }


            if (dataSearch.MinDate != null && dataSearch.MaxDate != null)
            {
                data = data.Where(a => a.CreateDate.Date >= dataSearch.MinDate && a.CreateDate.Date <= dataSearch.MaxDate).ToList();
            }

            if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
            {
                data = data.Where(a => a.Amount >= dataSearch.MinAmount && a.Amount <= dataSearch.MaxAmount).ToList();
            }

            ViewBag.Search = dataSearch;
            return View(data);
        }

        public IActionResult Create()
        {
            TblRole data = new TblRole();
            return PartialView(data);
        }

        public IActionResult Search()
        {
            return PartialView();
        }



    }
}

Xpos334/Xpos334/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.viewmodels;
using Xpos334.Services;

namespace Xpos334.Controllers
{
    public class RoleController : Controller
    {
        private RoleService roleService;
        private int IdUser = 1;

        public RoleController(RoleService _roleService)
        {
            roleService = _roleService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<TblRole> data = await roleService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.RoleName.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.RoleName).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.RoleName).ToList();
                    break;
            }

            return View(PaginatedList<TblRole>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));

        }


        public async Task<IActionResult> Index_MenuAccess(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.currentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<TblRole> data = await roleService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.RoleName!.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.RoleName).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.RoleName).ToList();
                    break;
            }

            return View(PaginatedList<TblRole>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }






        public async Task<JsonResult> CheckNameIsExist(string roleName, int id)
        {
            bool isExist = await roleService.CheckCategoryByName(roleName, id);
            return Json(isExist);
        }

        public IActionResult Create()
        {
            TblRole data = new TblRole();
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TblRole dataParam)
        {
            dataParam.CreatedBy = IdUser;
            VMResponse respon = await roleService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }


        public async Task<IActionResult> Edit(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }


        public async Task<IActionResult> Edit_MenuAccess(int id)
        {
            VMTblRole data = await roleService.GetDataById_MenuAccess(id);
            ViewBag.role_menu = data.role_menu;
            return PartialView(data);
        }



        [HttpPost]
        public async Task<IActionResult> Edit(TblRole dataParam)
        {
            dataParam.UpdatedBy = IdUser;
            VMResponse respon = await roleService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }


        [HttpPost]
        public async Task<IActionResult> Edit_MenuAccess(VMTblRole dataParam)
        {
            dataParam.UpdateBy = IdUser;
            VMResponse respon = await roleService.Edit_MenuAccess(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }


        public async Task<IActionResult> Detail(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }


        public async Task<IActionResult> Delete(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            int createBy = IdUser;
            VMResponse respon = await roleService.Delete(id, createBy);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return RedirectToAction("Index");
        }


        


    }
}

Xpos334/Xpos334/Views/Order/Catalog.cshtml
@using xpos334.viewmodels;


@model PaginatedList<VMTblProduct>

@{
    var data = @ViewBag.dataHeader;
}

<div class="row">
    <div class="col-lg-4 col-6">
        <div class="small-box bg-info">
            <div class="inner">
                <h3 id="totalproduct">
                    @{
                        if (data != null)
                        {
                            <span class="text-light">@data.TotalQty</span>
                        }
                        else
                        {
                            <span class="text-light">0</span>
                        }
                    }
                </h3>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a class="small-box-footer">
                <h5 class="text-light">Total Product</h5>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-6">
        <div class="small-box bg-success">
            <div class="inner">
                <h3 id="estimateprice">
                    @{
                        if (data != null)
                        {
                            <span class="text-light">@data.Amount</span>
                        }
                        else
                        {
                            <span class="text-light">0</span>
                        }
                    }
                </h3>
            </div>
            <div class="icon">
                <i class="ion ion-pricetag"></i>
            </div>
            <a class="small-box-footer">
                <h5 class="text-light">Estimate Price</h5>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-6">
        <div class="small-box bg-warning" id="btn_checkout">
            <div class="inner">
                <h3 class="text-light">Checkout</h3>

                <div class="icon">
                    <i class="ion ion-cash"></i>
                </div>
                <a class="small-box-footer">
                    <h5 class="text-light">More info</h5>
                </a>
            </div>
        </div>
    </div>
</div>


<div class="card-Header">
    <div class="card-tools">
        <button class="btn btn-primary" id="btn_search">
            <i class="fas fa-search"></i>
            Search
        </button>
    </div>
</div>


<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4">

            <div class="card card-primary card-outline">
                <div class="card-body box-profile">
                    <div class="text-center w-50">
                        <img class="profile-user-img img-fluid img-circle img-responsive" src="~/images/@item.Image" alt="User profile picture">
                    </div>
                    <h3 class="profile-username text-center" id="name_@item.Id">@item.NameProduct</h3>
                    <p class="text-muted text-center">@item.NameCategory / @item.NameVariant</p>
                    <ul class="list-group list-group-unbordered mb-3">
                        <li class="list-group-item">
                            <b>Price</b> <a class="float-right" id="price_@item.Id">@item.Price</a>
                        </li>
                        <li class="list-group-item">
                            <b>Stock</b> <a class="float-right" id="stock_@item.Id">@item.Stock</a>
                            <span class="text-danger" id="valid_stock_@item.Id"></span>
                        </li>
                    </ul>
                    <div class="row">
                        <div class="col-4">
                            <a id="min" dataid="@item.Id" class="btn btn-danger btn_min">
                                <b>-</b>
                            </a>
                        </div>
                        <div class="col-4 text-center">
                            <span class="text-lg" id="totalitem_@item.Id">0</span>
                        </div>
                        <div class="col-4">
                            <a id="plus" dataid="@item.Id" class="btn btn-success float-right btn_plus">
                                <b>+</b>
                            </a>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    }

</div>


<div class="card-footer">
    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }
    <div class="row">
        <div class="col-2">

            <form asp-action="Catalog" id="form_pagesize">
                <select name="PageSize" id="PageSize"
                        class="form-control">
                    <option value="3">3</option>
                    <option value="5">5</option>
                    <option value="10">10</option>
                </select>
            </form>
        </div>

        <div class="col-10">
            Page @Model.PageIndex of @Model.TotalPages
            <a id="aNext" asp-action="Catalog"
               asp-route-sortOrder="@ViewBag.CurrentSort"
               asp-route-pageNumber="@(Model.PageIndex + 1)"
               asp-route-currentFilter="@ViewBag.CurrentFilter"
               asp-route-pageSize="@ViewBag.CurrentPageSize"
               class="btn btn-info float-right @nextDisabled">
                Next
            </a>
            <a id="aPrev" asp-action="Catalog"
               asp-route-sortOrder="@ViewBag.CurrentSort"
               asp-route-pageNumber="@(Model.PageIndex - 1)"
               asp-route-currentFilter="@ViewBag.CurrentFilter"
               asp-route-pageSize="@ViewBag.CurrentPageSize"
               class="btn btn-info float-right @prevDisabled">
                Previous
            </a>
        </div>
    </div>
</div>


<script>
    let data = {}
    var totalproduct = parseInt($("#totalproduct").text())
    var estimateprice = parseInt($("#estimateprice").text())
    var obj = {}

    // SET LISTCHART First Load
    var ListCart = @Html.Raw(ViewBag.dataDetail)

        setTransaction()
    function setTransaction() {
        if (ListCart != null) {
            $.each(ListCart, function (index, element) {
                var id = element.IdProduct
                $("#totalitem_" + id).text(element.Qty)
                $("#stock_" + id).text(element.Stock)
            })
        }
    }

    $(".btn_plus").click(function () {
        if (ListCart == null || ListCart.length == 0) {
            ListCart = @Html.Raw(ViewBag.dataDetail)
                    }

        obj = {}

        var id = parseInt($(this).attr("dataid"))
        var idprice = "#price_" + id
        var idtotalitem = "#totalitem_" + id
        var idstock = "#stock_" + id
        var idname = "#name_" + id

        var totalitem = parseInt($(idtotalitem).text())
        var price = parseInt($(idprice).text())
        var stock = parseInt($(idstock).text())
        var nameProduct = $(idname).text()

        validateStock(id, stock)

        if (stock > 0) {
            totalproduct++
            totalitem++
            stock--
            estimateprice = estimateprice + price

            $("#totalproduct").text(totalproduct)
            $("#estimateprice").text(estimateprice)

            $(idstock).text(stock)
            $(idtotalitem).text(totalitem)
        }

        obj.IdProduct = id
        obj.Qty = totalitem
        obj.SumPrice = price * totalitem
        obj.Price = price
        obj.NameProduct = nameProduct
        obj.Stock = stock

        addList(id, obj)

        console.log(ListCart)

        setSession()
    })


    $(".btn_min").click(function () {
        if (ListCart == null || ListCart.length == 0) {
            ListCart = @Html.Raw(ViewBag.dataDetail)
                    }

        var id = parseInt($(this).attr("dataid"))
        var idprice = "#price_" + id
        var idtotalitem = "#totalitem_" + id
        var idstock = "#stock_" + id
        var idname = "#name_" + id


        var totalitem = parseInt($(idtotalitem).text())
        var price = parseInt($(idprice).text())
        var stock = parseInt($(idstock).text())
        var nameProduct = $(idname).text()


        if (totalitem > 0) {
            totalproduct--
            totalitem--
            stock++
            estimateprice = estimateprice - price

        }

        validateStock(id, stock)

        $("#totalproduct").text(totalproduct)
        $("#estimateprice").text(estimateprice)

        $(idtotalitem).text(totalitem)
        $(idstock).text(stock)

        obj.IdProduct = id
        obj.Qty = totalitem
        obj.SumPrice = price * totalitem
        obj.Price = price
        obj.NameProduct = nameProduct
        obj.Stock = stock

        spliceList(id, obj)

        console.log(ListCart)

        setSession()
    })

    function addList(id, obj) {
        const index = ListCart.map(e => e.IdProduct).indexOf(id);

        if (index == -1) {
            ListCart.push(obj)
        }
        else {
            ListCart[index].Qty = obj.Qty
            ListCart[index].Stock = obj.Stock
            ListCart[index].SumPrice = obj.SumPrice
        }
    }

    function spliceList(id, obj) {
        const index = ListCart.map(e => e.IdProduct).indexOf(id);

        if (index != -1) {
            ListCart[index].Qty = obj.Qty
            ListCart[index].Stock = obj.Stock
            ListCart[index].SumPrice = obj.SumPrice

            if (obj.Qty == 0) {
                ListCart.splice(index, 1)
            }
        }
    }

    function validateStock(id, stock) {

        if (stock == 0) {
            $("#valid_stock_" + id).text("out of stock")
        }
        else {
            $("#valid_stock_" + id).empty()
        }
    }

    function setSession() {
        data = {
            TotalQty: totalproduct,
            Amount: estimateprice,
            ListDetails: ListCart
        }

        data.namacustomer = ""
        data.idcustomer = 1

        $.ajax({
            url: "/Order/SetSession",
            data: { dataHeader: data },
            type: "post",
            dataType: "json",
            success: function (respon) {
                //alert("set session done")
            }
        })
    }

    $("#btn_checkout").click(function () {

        data = {
            TotalQty: totalproduct,
            Amount: estimateprice,
            ListDetails: ListCart
        }

        $("#modal_body").empty();

    @* modal diperbesar dengan add class *@
            $(".modal-dialog").addClass("modal-lg")

        if (ListCart.length > 0) {
            $("#modal_body").load("/Order/OrderPreview", data)
        }
        else {
            $("#modal_body").text("please select product before")
        }
        $("#my_modal").modal("show");
    })

    $("#btn_search").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/Order/SearchMenu")
        $("#my_modal").modal("show")

    @* modal diperbesar *@
            $(".modal-dialog").removeClass("modal-lg")
    })

    $("#PageSize").val(@ViewBag.CurrentPageSize)
    $("#PageSize").change(function () {
        $("#form_pagesize").submit()
    })
</script>

Xpos334/Xpos334/Views/Order/Create.cshtml
@using xpos334.datamodels;
@model TblRole;

@{
    ViewData["Title"] = "Create Role";
}
<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>
        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row">
                <label for="RoleName" class="col-sm-4 col-form-label">Role name</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="RoleName" name="RoleName" value="@Model.RoleName">
                    <span id="validate_RoleName" class="text-danger"></span>
                </div>
            </div>



            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" asp-controller="Role" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            RoleName: {
                required: true,
                minlength: 3,
            }

        },
        messages: {
            RoleName: {
                required: "Please insert Role Name",
                minlength: "Please Insert at least 3 character"
            }
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize()
            var roleName = $("#RoleName").val()
            var id = 0;

            $.ajax({
                url: "/Role/CheckNameIsExist",
                type: "get", //type atau method sama aja.
                data: { roleName: roleName, id: id },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_RoleName").text("Role Name Already Axists")
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })

    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Role/Create",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_modal").modal("hide")

                    Swal.fire({
                        title: "Information!",
                        text: data.message,
                        icon: "success"
                    }).then((result) => {
                        if (result.value) {
                            window.location.reload();
                        }
                    });
                }
                else {
                    toastr.errorClass(data.message)
                }

            }
        })
    }
</script>

Xpos334/Xpos334/Views/Order/HistoryOrder.cshtml
@using Xpos334.Services;
@using xpos334.viewmodels;



@inject OrderService orderService
@model List<VMOrderHeader>

@{
    List<VMOrderDetail> detail = new List<VMOrderDetail>();
    VMSearchPage search = ViewBag.Search;
}

@if (search.CodeTransaction != null || search.MinDate != DateTime.MinValue || search.MinAmount != decimal.MinValue)
{
    <div class="info-box bg-light">
        <div class="info-box-content">
            <div class="info-box-text text-muted">
                Search Result :
                @if (search.CodeTransaction != null)
                {
                    <p>Code Transaction &nbsp; : @search.CodeTransaction</p>
                }
                @if (search.MinDate != DateTime.MinValue)
                {
                    <p>Min Date &nbsp; : @search.MinDate?.ToString("dd-MM-yyyy")</p>
                }
                @if (search.MaxDate != DateTime.MaxValue)
                {
                    <p>Max Date &nbsp; : @search.MaxDate?.ToString("dd-MM-yyyy")</p>
                }
                @if (search.MinAmount != decimal.MinValue)
                {
                    <p>Min Amount &nbsp; : @search.MinAmount</p>
                }
                @if (search.MaxAmount != decimal.MaxValue)
                {
                    <p>Max Amount &nbsp; : @search.MaxAmount</p>
                }
            </div>
        </div>
    </div>
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">History Order (@ViewBag.Count)</h3>
        <div class="card-tools">
            <button class="btn btn-primary" id="btn_search">
                <i class="fas fa-search"></i>
                Search
            </button>
        </div>
    </div>
    <div class="card-body p-0">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Order Date</th>
                    <th>Code Transaction</th>
                    <th>Total Qty</th>
                    <th>Amount</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.CreateDate.ToString("dd-MM-yyyy")</td>
                        <td>@item.CodeTransaction</td>
                        <td>@item.TotalQty</td>
                        <td>Rp. @item.Amount.ToString("#,#0.00")</td>
                        <td>
                            @* pake collapse pada bootstrap *@
                            <a class="btn btn-primary btn_more w-50" id="btn_more_@item.Id" dataid="@item.Id" data-toggle="collapse"
                               href="#collapse_id_@item.Id" role="button" aria-expanded="false" aria-controls="collapseExample">
                                Show More
                            </a>
                        </td>
                    </tr>

                    <tr class="collapse" id="collapse_id_@item.Id">
                        <td colspan="5">
                            <div class="card card-body">
                                @{
                                    //kalo ngga manngil pake list didalam VMOrderHeader contohh
                                    // tinggal buat fungsi untuk ngambil detail orderannya di service "ListDetail"
                                    // @{
                                    //     detail = await orderService.ListDetails(@item.Id);
                                    // }
                                    <table class="table table-hover">
                                        <thead>
                                            <tr class="table-primary">
                                                <th>Product</th>
                                                <th>Price</th>
                                                <th>Qty</th>
                                                <th>Subtotal</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            @foreach (var dt in item.ListDetails)
                                            {
                                                <tr>
                                                    <th>@dt.NameProduct</th>
                                                    <th>Rp. @dt.Price.ToString("#,#0.00")</th>
                                                    <th>@dt.Qty</th>
                                                    <th>Rp. @dt.SumPrice.ToString("#,#0.00")</th>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                }


                            </div>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>

</div>


<script>
    $(".btn_more").click(function () {
        var id = $(this).attr("dataid")
        var txt = $("#btn_more_" + id).text().trim()  //trim() fungsi ngilangin spasi kiri kanan!

        if (txt == "Show More") {
            $("#btn_more_" + id).text("Hide")
            $("#btn_more_" + id).removeClass("btn-primary")
            $("#btn_more_" + id).addClass("btn-danger")
        }
        else {
            $("#btn_more_" + id).text("Show More")
            $("#btn_more_" + id).removeClass("btn-danger")
            $("#btn_more_" + id).addClass("btn-primary")
        }
    })


    $("#btn_search").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/Order/Search")
        $("#my_modal").modal("show")
    })
</script>