Xpos334/Xpos334/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.viewmodels;
using Xpos334.Services;

namespace Xpos334.Controllers
{
    public class CategoryController : Controller
    {
        private CategoryService categoryService;
        private int IdUser = 1;

        public CategoryController(CategoryService _categoryService)
        {
            categoryService = _categoryService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<TblCategory> data = await categoryService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameCategory.ToLower().Contains(searchString.ToLower())
                    || a.Description.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameCategory).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameCategory).ToList();
                    break;
            }

            return View(PaginatedList<TblCategory>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));

        }

        public IActionResult Create()
        {
            TblCategory data = new TblCategory();
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TblCategory dataParam)
        {
            dataParam.CreateBy = IdUser;
            VMResponse respon = await categoryService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<JsonResult> CheckNameIsExist(string nameCategory, int id)
        {
            bool isExist = await categoryService.CheckCategoryByName(nameCategory, id);
            return Json(isExist);
        }

        public async Task<IActionResult> Edit(int id)
        {
            TblCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(TblCategory dataParam)
        {
            dataParam.UpdateBy = IdUser;
            VMResponse respon = await categoryService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            TblCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            TblCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            int createBy = IdUser;
            VMResponse respon = await categoryService.Delete(id, createBy);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return RedirectToAction("Index");
        }

    }
}

Xpos334/Xpos334/Views/Category/Create.cshtml
@{
    ViewData["Title"] = "Create Category";
}
<div class="card">   
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>
        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
                    <span id="validate_NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <textarea type="text" class="form-control" id="Description" name="Description">@Model.Description</textarea>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" asp-controller="Category" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
        $("#form_input").validate({
            errorClass: "text-danger",
            rules: {
                NameCategory: {
                    required: true,
                    minlength: 3,
                }

            },
            messages: {
                NameCategory: {
                    required: "Please insert Name Category",
                    minlength: "Please Insert at least 3 character"
                }
            },
            submitHandler: function(form){
                
                var dataForm = $(form).serialize()
                var nameCategory = $("#NameCategory").val()
                var id = 0;

                $.ajax({
                    url:"/Category/CheckNameIsExist",
                    type:"get", //type atau method sama aja.
                    data: {nameCategory: nameCategory, id: id},
                    dataType: "json",
                    success:function(respon){
                        if (respon) {
                            $("#validate_NameCategory").text("Name Category Already Axists")
                            return true;
                        }
                        else {
                            fungsiSubmit(dataForm)
                        }
                    }

                })
            }
        })

    function fungsiSubmit(dataParam) { 
        $.ajax({
            url:"/Category/Create",
            type:"post",
            data: dataParam,
            dataType: "json",
            success: function(respon) {
                var data = respon.dataRespon
                if (data.success) 
                {
                    $("#my_modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.message)
                }

            }
        })
    }
</script>

Xpos334/Xpos334/Views/Category/Delete.cshtml
@using xpos334.datamodels
@model TblCategory
@{
    ViewData["Title"] = "Delete Category";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post" id="form_delete">
            <input type="hidden" id="Id" name="Id" value="@Model.Id"/>
            <h3 class="">Are you sure to delete this data <br />@Model.NameCategory</h3>
            <div class="modal-footer">   
                <button type="submit" class="btn btn-primary">Yes?</button>
                <a asp-controller="Category" asp-action="Index" class="btn btn-light">No</a>
            </div>


        </form>
    </div>
</div>


<script>
    $("#form_delete").validate({
        submitHandler: function (form) {
          //  var dataParam = $(form)
          var id = $("#Id").val()

          $.ajax({
              url:'/Category/SureDelete',
              type:"post",
              data: {id : id},
              dataType: "json",
              success: function(respon){
                  var data = respon.dataRespon
                  if (data.success) 
                  {
                      $("#my_modal").modal("hide")
                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                  }
                    else {
                        toastr.errorClass(data.message)
                    }
              }

          })
        }
    })
</script>

Xpos334/Xpos334/Views/Category/Detail.cshtml
@using xpos334.datamodels;
@model TblCategory

@{

    ViewData["Title"] = "Detail Category";
}


<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>


            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
                    <span id="validate_NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <textarea type="text" class="form-control" id="Description" name="Description" readonly>@Model.Description</textarea>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-10">
                    <a class=" btn btn-outline-primary" asp-controller="Category" asp-action="Index">Back To List</a>
                </div>
            </div>

    </div>
</div>

Xpos334/Xpos334/Views/Category/Edit.cshtml
@using xpos334.datamodels;
@model TblCategory

@{

    ViewData["Title"] = "Edit Category";
}


<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>
        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">


            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
                    <span id="validate_NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <textarea type="text" class="form-control" id="Description" name="Description">@Model.Description</textarea>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" asp-controller="Category" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameCategory: {
                required: true,
                minlength: 3,
            }

        },
        messages: {
            NameCategory: {
                required: "Please insert Name Category",
                minlength: "Please Insert at least 3 character"
            }
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize()
            var nameCategory = $("#NameCategory").val()
            var id = $("#Id").val();

            $.ajax({
                url: "/Category/CheckNameIsExist",
                type: "get", //type atau method sama aja.
                data: { nameCategory: nameCategory, id: id },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_NameCategory").text("Name Category Already Axists")
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })

    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Category/Edit",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.message)
                }

            }
        })
    }
</script>

Xpos334/Xpos334/Views/Category/Index.cshtml
@using xpos334.datamodels;
@using xpos334.viewmodels;
@model PaginatedList<TblCategory>
@{
    ViewData["Title"] = "Category";
}


<div class="card">
    <div class="card-body">
        <h1 class="card-title">@ViewData["Title"]</h1>

        <div class="row mb-3">
            <div class="col-12">
                <div class="d-flex justify-content-between">
                    <button id="btn_create" class="btn btn-primary">Create</button>

                    <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">

                    <div class="input-group w-100">
                        <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search..."/>
                        <div class="input-group-prepend">
                            <button type="submit" class="input-group-text" title="search">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                        <div class="input-group-prepend">
                            <a class="input-group-text" asp-action="Index" title="reset">
                                <i class="fas fa-redo"></i>
                            </a>                           
                        </div>

                    </div>
                    </form>
                </div>
            </div>
        </div>

        <table class="table table-hover mb-3">
            <thead>
                <tr>
                    <th>

                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort"
                           asp-route-currentFilter="@ViewBag.CurrentFilter"
                           asp-route-pageNumber="@ViewBag.CurrentPageSize"
                        class="text-decoration-none">
                            Name Variant
                        </a>
                    </th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if(Model.Count != 0)
                {
                    @foreach(var item in Model)
                    {
                        <tr>
                            <td>@item.NameCategory</td>
                            <td>@item.Description</td>
                            <td>
                                <a class="btn btn-warning btn_edit text-white" dataid="@item.Id">Edit</a>
                                <a class="btn btn-info btn_detail text-white" dataid="@item.Id">Detail</a>
                                <a class="btn btn-danger btn_delete text-white" dataid="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>
                            Data Not Found!
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disable" : "";
        }
        <div class="row">
            <div class="col-2">
                <form asp-action="Index" id="form_pagesize">
                    <select name="PageSize" id="PageSize" class="form-control">
                        <option value="3">3</option>
                        <option value="5">5</option>
                        <option value="10">10</option>
                    </select>
                </form>
            </div>
            <div class="col-10">
                Page @Model.PageIndex of @Model.TotalPages
                <a asp-action="Index"
                asp-route-sortOrder="ViewBag.CurrentSort"
                asp-route-pageNumber="@(Model.PageIndex + 1)"
                asp-route-currentFilter ="@ViewBag.CurrentFiler"
                asp-route-pageSize="@ViewBag.CurrentPageSize" class=" btn btn_info float-right @nextDisabled"
                >Next</a>
                <a asp-action="Index"
                   asp-route-sortOrder="ViewBag.CurrentSort"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewBag.CurrentFiler"
                   asp-route-pageSize="@ViewBag.CurrentPageSize" class=" btn btn_info float-right @prevDisabled">Next</a>
            </div>
        </div>
    </div>

</div>

<script>


    



    $("#btn_create").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/Category/Create")
        $("#my_modal").modal("show")
    })

    $(".btn_edit").click(function () {
        var id = $(this).attr("dataid")
        $("#modal_body").empty()
        $("#modal_body").load("/Category/Edit?id="+id)
        $("#my_modal").modal("show")
    })

    $(".btn_detail").click(function () {
        var id = $(this).attr("dataid")
        $("#modal_body").empty()
        $("#modal_body").load("/Category/Detail?id=" + id)
        $("#my_modal").modal("show")
    })


    $(".btn_delete").click(function () {
        var id = $(this).attr("dataid")
        $("#modal_body").empty()
        $("#modal_body").load("/Category/Delete?id=" + id)
        $("#my_modal").modal("show")
    })

    $("#PageSize").val(@ViewBag.CurrentPageSize)
    $("#PageSize").change(function()
    {
        $("#form_pagesize").submit()
    })

</script>               