Xpos334/Xpos334/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.viewmodels;
using Xpos334.Services;

namespace Xpos334.Controllers
{
    public class VariantController : Controller
    {
        private CategoryService categoryService;
        private VariantService variantService;
        private int IdUser = 1;

        public VariantController(CategoryService _categoryService, VariantService _variantService)
        {
            categoryService = _categoryService;
            this.variantService = _variantService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<VMTblVariant> data = await variantService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower())
                    || a.NameCategory.ToLower().Contains(searchString.ToLower())
                    || a.Description.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameVariant).ToList();
                    break;
            }

            return View(PaginatedList<VMTblVariant>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));

        }
        public async Task<IActionResult> Create()
        {
            VMTblVariant data = new VMTblVariant();

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;    

            return PartialView(data);
        }

        public async Task<JsonResult> CheckNameIsExist(string name, int id, int idCategory)
        {
            bool isExist = await variantService.CheckByName(name, id, idCategory);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMTblVariant dataParam)
        {
            dataParam.CreateBy = IdUser;
            VMResponse respon = await variantService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }


        public async Task<IActionResult> Edit(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblVariant dataParam)
        {
            VMResponse respon = await variantService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
              return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await variantService.Delete(id);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return RedirectToAction("Index");
        }



        public async Task<IActionResult> MultipleDelete(List<int> listId)
        {
            List<string> listName = new List<string>();
            foreach (var item in listId)
            {
                VMTblVariant data = await variantService.GetDataById(item);
                listName.Add(data.NameVariant);
            }

            ViewBag.ListName = listName;
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> SureMultipleDelete(List<int> listId)
        {
            VMResponse respon = await variantService.MultipleDelete(listId);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return RedirectToAction("Index");
        }







    }
}

Xpos334/Xpos334/Views/Variant/Create.cshtml
@using xpos334.viewmodels;
@model VMTblVariant

@{
    ViewData["Title"] = "Create Variant";
}

<div class=" card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>
        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">
                    <span id="validate_NameVariant" class="text-danger"></span>
                </div>
            </div><div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                </div>
                @Html.DropDownList(
                "IdCategory", new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),
                "--Pilih Kategory--",
                new { @class = "form-control"}
                )
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" asp-controller="Variant" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>



    </div>
</div>


<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameVariant: {
                required: true,
                minlength: 3,
            },
            IdCategory: "required"
        },
        messages: {
            NameVariant: {
                required: "Please fill Name Variant",
                minlength: "The name must consist of at least 3 character"
            },
            IdCategory: "Please select category"
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize()

            var name = $("#NameVariant").val()
            var id = 0
            var idCategory = $("#IdCategory").val()

            $.ajax({
                url: "/Variant/CheckNameIsExist",
                type: "get", //type atau method sama aja.
                data: { name: name, id: id, idCategory: idCategory },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_NameVariant").text("Name Variant Already Exists");
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })

    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Variant/Create",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.message)
                }

            }
        })
    }
</script>

Xpos334/Xpos334/Views/Variant/Delete.cshtml
    @using xpos334.viewmodels;
    @model VMTblVariant;


    @{
        ViewData["Title"] = "Delete Variant";
    }


    <div class="card">
        <div class="card-body">

            <form asp-action="SureDelete" method="post" id="form_delete">
                <input type="hidden" id="Id" name="Id" value="@Model.Id" />
                <h3 class="">Are you sure to delete this data <br />@Model.NameVariant</h3>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Yes?</button>
                    <a asp-controller="Variant" asp-action="Index" class="btn btn-light">No</a>
                </div>


            </form>
        </div>
    </div>


    <script>
        $("#form_delete").validate({
            submitHandler: function (form) {

                var id = $("#Id").val()
               // var dataParam = $(form).serialize()    ---> contoh kalo make form
                $.ajax({
                    url: '/Variant/SureDelete',
                    type: "post",
                    data: { id: id },
                    dataType: "json",
                    success: function (respon) {
                        var data = respon.dataRespon
                        if (data.success) {
                            $("#my_modal").modal("hide")
                            toastr.success(
                                data.message,
                                '',
                                {
                                    timeOut: 500,
                                    fadeOut: 500,
                                    onHidden: function () {
                                        window.location.reload()
                                    }
                                }
                            )
                        }
                        else {
                            toastr.errorClass(data.message)
                        }
                    }

                })
            }
        })
    </script>

Xpos334/Xpos334/Views/Variant/Detail.cshtml
﻿@using xpos334.viewmodels;
@model VMTblVariant

@{
    Layout = null;
    ViewData["Title"] = "Detail Variant";
}

<div class="card">
    <div class="card-body">

        @* <div class="h4 mb-4">@ViewData["Title"]</div> *@
        <div class="card-title">@ViewData["Title"]</div>



            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant" readonly>
        
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                <input type="text" class="form-control" id="NameCategory" name="NameCategoty" value="@Model.NameCategory" readonly>

                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back to List</a>
                </div>
            </div>

    </div>
</div>

Xpos334/Xpos334/Views/Variant/Edit.cshtml
﻿@using xpos334.viewmodels;
@model VMTblVariant

@{
    Layout = null;
    ViewData["Title"] = "Edit Variant";
}

<div class="card">
    <div class="card-body">

        @* <div class="h4 mb-4">@ViewData["Title"]</div> *@
        <div class="card-title">@ViewData["Title"]</div>

        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">


            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">
                    <span id="validate_NameVariant" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory,"Id","NameCategory"),
                    "--Pilih Category--",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    @* <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description"> *@
                    <textarea type="text" class="form-control" id="Description" Name="Description">@Model.Description</textarea>

                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameVariant: {
                required: true,
                minlength: 3,
            },
            IdCategory: "required"
        },
        messages: {
            NameVariant: {
                required: "Please fill Name Variant",
                minlength: "The name must consist of at least 3 character"
            },
            IdCategory: "Please select category"
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize()

            var name = $("#NameVariant").val()
            var id = $("#Id").val()
            var idCategory = $("#IdCategory").val()

            $.ajax({
                url: "/Variant/CheckNameIsExist",
                type: "get", //type atau method sama aja.
                data: { name: name, id: id, idCategory: idCategory },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_NameVariant").text("Name Variant Already Exists");
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })

    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Variant/Edit",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.message)
                }

            }
        })
    }
</script>

Xpos334/Xpos334/Views/Variant/Index.cshtml
@using xpos334.viewmodels;

@model PaginatedList<VMTblVariant>
@{
    ViewData["Title"] = "Variant";
}

<div class="card">
    <div class="card-body">
        <h1 class="card-title">@ViewData["Title"]</h1>

        <div class="row mb-3">
            <div class="col-12">
                <div class="d-flex justify-content-between">
                    <button id="btn_create" class="btn btn-primary">Create</button>
                    <button id="btn_multiple_delete" class="btn btn-danger" disabled>Hapus Multiple</button>
                    <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">

                        <div class="input-group w-100">
                            <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search..." />
                            <div class="input-group-prepend">
                                <button type="submit" class="input-group-text" title="search">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                            <div class="input-group-prepend">
                                <a class="input-group-text" asp-action="Index" title="reset">
                                    <i class="fas fa-redo"></i>
                                </a>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>

        <table class="table table-hover mb-3">
            <thead>
                <tr>
                    <th>#</th>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort"
                           asp-route-currentFilter="@ViewBag.CurrentFilter"
                           asp-route-pageNumber="@ViewBag.CurrentPageSize"
                           class="text-decoration-none">
                            Name Category
                        </a>
                    </th>
                    <th>Name Variant</th>
                    <th>Description</th>
                    <th>IsDelete</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count != 0)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td><input type="checkbox" onchange="selectedItem()" class="mychecked" value="@item.Id" /></td>
                            <td>@item.NameCategory</td>
                            <td>@item.NameVariant</td>
                            <td>@item.Description</td>
                            <td>
                                @if(item.IsDelete == true)
                                {
                                    <input type="checkbox" disabled checked/>
                                }
                                else
                                {
                                    <input type="checkbox" disabled />

                                }
                            </td>
                            <td>
                                <a class="btn btn-warning btn_edit text-white" dataid="@item.Id">Edit</a>
                                <a class="btn btn-info btn_detail text-white" dataid="@item.Id">Detail</a>
                                <a class="btn btn-danger btn_delete text-white" dataid="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>
                            Data Not Found!
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disable" : "";
        }
        <div class="row">
            <div class="col-2">
                <form asp-action="Index" id="form_pagesize">
                    <select name="PageSize" id="PageSize" class="form-control">
                        <option value="3">3</option>
                        <option value="5">5</option>
                        <option value="10">10</option>
                    </select>
                </form>
            </div>
            <div class="col-10">
                Page @Model.PageIndex of @Model.TotalPages
                <a asp-action="Index"
                   asp-route-sortOrder="ViewBag.CurrentSort"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewBag.CurrentFiler"
                   asp-route-pageSize="@ViewBag.CurrentPageSize" class=" btn btn_info float-right @nextDisabled">Next</a>
                <a asp-action="Index"
                   asp-route-sortOrder="ViewBag.CurrentSort"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewBag.CurrentFiler"
                   asp-route-pageSize="@ViewBag.CurrentPageSize" class=" btn btn_info float-right @prevDisabled">Prev</a>
            </div>  
        </div>
    </div>

</div>

<script>


    var listId = []

    function selectedItem() {
        var mychecked = $(".mychecked")
        listId = []
        for (var i = 0; i < mychecked.length; i++) {
            if (mychecked[i].checked) {
                listId.push(mychecked[i].value)
            }
        }

        if (listId.length > 0) {
            $("#btn_multiple_delete").attr("disabled", false)
        }
        else {
            $("#btn_multiple_delete").attr("disabled", true)
        }
    }

    $("#btn_multiple_delete").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/variant/MultipleDelete", { listId: listId })
        $("#my_modal").modal("show")
    })


    $("#btn_create").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/Variant/Create")
        $("#my_modal").modal("show")
    })

    $(".btn_edit").click(function () {
        var id = $(this).attr("dataid")
        $("#modal_body").empty()
        $("#modal_body").load("/Variant/Edit?id=" + id)
        $("#my_modal").modal("show")
    })
    $(".btn_delete").click(function () {
        var id = $(this).attr("dataid")
        $("#modal_body").empty()
        $("#modal_body").load("/Variant/Delete?id=" + id)
        $("#my_modal").modal("show")
    })
    $(".btn_detail").click(function () {
        var id = $(this).attr("dataid")
        $("#modal_body").empty()
        $("#modal_body").load("/Variant/Detail?id=" + id)
        $("#my_modal").modal("show")
    })
 
    $("#PageSize").val(@ViewBag.CurrentPageSize)
    $("#PageSize").change(function () {
        $("#form_pagesize").submit()
    })
</script>

Xpos334/Xpos334/Views/Variant/MultipleDelete.cshtml
﻿
@{
    ViewData["Title"] = "Multiple Delete Variant";
}

<div class="card">
    <div class="card-body">
        <form asp-action="SureMultipleDelete" method="post" id="form_delete">
            <h3>Are you sure for delete ?</h3>
            @foreach (var item in ViewBag.ListName)
            {
                <h4>@item</h4>
            }
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-controller="Variant" asp-action="Index" class="btn btn-cyan">No</a>
            </div>
        </form>
    </div>
</div>

<script>
    $("#form_delete").validate({
        submitHandler: function (form) {

            $.ajax({
                url: '/Variant/SureMultipleDelete',
                type: "post",
                data: { listId: listId },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#my_modal").modal("hide")
                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        toastr.errorClass(data.message)
                    }
                }
            })
        }
    })
</script>